// Example config - This file is generated by scripts/generate-ai-config.mjs
// Source: .env file
// DO NOT commit the actual config.ts file (it's gitignored)

// TWO WAYS TO CONFIGURE:
//
// 1. DEVELOPMENT (direct API - API key in bundle):
//    GROQ_API_KEY=gsk_xxxxxxxxxxxx
//    GROQ_WORKER_URL=
//
// 2. PRODUCTION (Cloudflare Worker - no API key in bundle):
//    GROQ_API_KEY=
//    GROQ_WORKER_URL=https://your-worker.workers.dev
//    Setup worker: See workers/README.md

export const AI_CONFIG = {
  GROQ_API_KEY: "",
  GROQ_WORKER_URL: "",
  GROQ_MODEL: "qwen/qwen3-32b",
  ENABLED: false
} as const;
